const skills = [
  'JavaScript',
  'HTML/CSS',
  'React.js',
  'Angular',
  'Vue.js',
  'TypeScript',
  'Mobile Development',
  'Cloud Computing',
  'Web Development',
  'Python',
  'C++',
  'Java',
  'C#',
  'PHP',
  'Ruby',
  'Swift',
  'Kotlin',
  'Dart',
  'Flutter',
  'React Native',
  'Ionic',
  'Xamarin',
  'Unity',
  'Game Development',
  'Docker',
  'Kubernetes',
  'Jenkins',
  'Git',
  'SVN',
  'Agile Methodologies',
  'Scrum',
  'Kanban',
  'DevOps',
  'Machine Learning',
  'Deep Learning',
  'Artificial Intelligence',
  'Data Science',
  'Big Data',
  'Data Engineering',
  'Natural Language Processing',
  'Computer Vision',
  'Reinforcement Learning',
  'Blockchain',
  'Ethereum',
  'Solidity',
  'Hyperledger',
  'Cryptocurrencies',
  'Cyber Security',
  'Penetration Testing',
  'Network Security',
  'Encryption',
  'Incident Response',
  'Forensics',
  'Malware Analysis',
  'Vulnerability Assessment',
  'Risk Management',
  'Compliance',
  'GDPR',
  'PCI DSS',
  'ISO 27001',
  'NIST',
  'ITIL',
  'Project Management',
  'Agile Project Management',
  'Waterfall Project Management',
  'PMP',
  'PRINCE2',
  'Six Sigma',
  'Lean Management',
  'Communication',
  'Teamwork',
  'Leadership',
  'Emotional Intelligence',
  'Conflict Resolution',
  'Time Management',
  'Negotiation',
  'Decision Making',
  'Critical Thinking',
  'Problem Solving',
  'Creativity',
  'Adaptability',
  'Stress Management',
  'Self-Motivation',
  'Resilience',
  'Attention to Detail',
  'Analytical Skills',
  'Numerical Skills',
  'Technical Writing',
  'Documentation',
  'Presentation Skills',
  'Public Speaking',
  'Technical Support',
  'Customer Service',
  'Sales',
  'Marketing',
  'Finance',
  'Accounting',
  'Human Resources',
  'Recruitment',
  'Employee Relations',
  'Training and Development',
  'Performance Management',
  'Workforce Planning',
  'Compensation and Benefits',
  'Talent Management',
  'Organizational Development',
  'Strategic Planning',
  'Business Analysis',
  'Market Research',
  'Competitive Analysis',
  'Financial Analysis',
  'Risk Analysis',
  'Business Intelligence',
  'Data Visualization',
  'Reporting',
  'Project Planning',
  'Requirements Gathering',
  'Stakeholder Management',
  'Quality Assurance',
  'User Experience Design',
  'User Interface Design',
  'Wireframing',
  'Prototyping',
  'Usability Testing',
  'Accessibility',
  'A/B Testing',
  'Search Engine Optimization',
  'Social Media Marketing',
  'Email Marketing',
  'Content Marketing',
  'Digital Marketing',
  'Affiliate Marketing',
  'Pay Per Click',
  'Customer Relationship Management',
  'Lead Generation',
  'Salesforce',
  'HubSpot',
  'Mailchimp',
  'Google Analytics',
  'Adobe Creative Suite',
  'Photoshop',
  'Illustrator',
  'InDesign',
  'After Effects',
  'Premiere Pro',
  'Audition',
  'Final Cut Pro',
  'Logic Pro',
  'Ableton Live',
  'Pro Tools',
  'Studio One',
];

export { skills };