export const Skills = [
    "Python",
    "JavaScript",
    "Java",
    "C++",
    "C#",
    "Ruby",
    "Swift",
    "Kotlin",
    "TypeScript",
    "Go",
    "PHP",
    "HTML",
    "CSS",
    "SQL",
    "MATLAB",
    "R",
    "Scala",
    "Rust",
    "Perl",
    "Bash",
    "React.js",
    "Angular",
    "Vue.js",
    "Node.js",
    "Express.js",
    "Django",
    "Flask",
    "ASP.NET",
    "RESTful APIs",
    "GraphQL",
    "WebSocket",
    "React Native",
    "Flutter",
    "iOS Development (Swift)",
    "Android Development (Java/Kotlin)",
    "Xamarin",
    "MySQL",
    "PostgreSQL",
    "MongoDB",
    "SQLite",
    "Oracle",
    "Microsoft SQL Server",
    "Redis",
    "Cassandra",
    "Amazon Web Services (AWS)",
    "Microsoft Azure",
    "Google Cloud Platform (GCP)",
    "Docker",
    "Kubernetes",
    "Terraform",
    "Serverless Framework",
    "Hadoop",
    "Apache Spark",
    "Apache Kafka",
    "Apache HBase",
    "Apache Flink",
    "MapReduce",
    "Hive",
    "Pig",
    "Storm",
    "TensorFlow",
    "PyTorch",
    "scikit-learn",
    "Keras",
    "Pandas",
    "NumPy",
    "Matplotlib",
    "NLTK",
    "OpenCV",
    "Spark MLlib",
    "H2O.ai",
    "Jenkins",
    "Travis CI",
    "CircleCI",
    "GitLab CI",
    "GitHub Actions",
    "Ansible",
    "Chef",
    "Puppet",
    "Docker",
    "Kubernetes",
    "Terraform",
    "Vagrant",
    "TCP/IP",
    "DNS",
    "DHCP",
    "HTTP",
    "HTTPS",
    "VPN",
    "VLAN",
    "LAN",
    "WAN",
    "OSI model",
    "Routing Protocols (BGP, OSPF, RIP)",
    "Wireshark",
    "Ethical Hacking",
    "Penetration Testing",
    "Network Security",
    "Cryptography",
    "Firewalls",
    "Intrusion Detection Systems (IDS)",
    "Security Information and Event Management (SIEM)",
    "Vulnerability Assessment",
    "Threat Intelligence",
    "Linux (Ubuntu, CentOS, Debian, Red Hat)",
    "Windows Server",
    "MacOS",
    "Unix",
    "Git",
    "SVN",
    "Mercurial",
    "Unit Testing",
    "Integration Testing",
    "Regression Testing",
    "Load Testing",
    "Performance Testing",
    "Test Automation (Selenium, Cypress, Appium)",
    "Adobe XD",
    "Sketch",
    "Figma",
    "Wireframing",
    "Prototyping",
    "Usability Testing",
    "User Research",
    "Responsive Design",
    "Scrum",
    "Kanban",
    "Lean",
    "Agile Development",
    "Agile Project Management Tools (Jira, Trello, Asana)",
    "Arduino",
    "Raspberry Pi",
    "AVR Microcontrollers",
    "ARM Architecture",
    "Embedded C",
    "FPGA",
    "Ethereum",
    "Solidity",
    "Smart Contracts",
    "Hyperledger Fabric",
    "Corda",
    "Blockchain Development",
    "Qiskit",
    "Cirq",
    "Quantum Algorithms",
    "Quantum Gates",
    "Quantum Circuit Design"
  ];
  