export const Skills = Object.freeze([
  "Python",
  "JavaScript",
  "Java",
  "C++",
  "C#",
  "Ruby",
  "Swift",
  "Kotlin",
  "TypeScript",
  "Go",
  "PHP",
  "HTML",
  "CSS",
  "SQL",
  "MATLAB",
  "R",
  "Scala",
  "Rust",
  "Perl",
  "Bash",
  "React.js",
  "Angular",
  "Vue.js",
  "Node.js",
  "Express.js",
  "Django",
  "Flask",
  "ASP.NET",
  "RESTful APIs",
  "GraphQL",
  "WebSocket",
  "React Native",
  "Flutter",
  "iOS Development (Swift)",
  "Android Development (Java/Kotlin)",
  "Xamarin",
  "MySQL",
  "PostgreSQL",
  "MongoDB",
  "SQLite",
  "Oracle",
  "Microsoft SQL Server",
  "Redis",
  "Cassandra",
  "Amazon Web Services (AWS)",
  "Microsoft Azure",
  "Google Cloud Platform (GCP)",
  "Docker",
  "Kubernetes",
  "Terraform",
  "Serverless Framework",
  "Hadoop",
  "Apache Spark",
  "Apache Kafka",
  "Apache HBase",
  "Apache Flink",
  "MapReduce",
  "Hive",
  "Pig",
  "Storm",
  "TensorFlow",
  "PyTorch",
  "scikit-learn",
  "Keras",
  "Pandas",
  "NumPy",
  "Matplotlib",
  "NLTK",
  "OpenCV",
  "Spark MLlib",
  "H2O.ai",
  "Jenkins",
  "Travis CI",
  "CircleCI",
  "GitLab CI",
  "GitHub Actions",
  "Ansible",
  "Chef",
  "Puppet",
  "Docker",
  "Kubernetes",
  "Terraform",
  "Vagrant",
  "TCP/IP",
  "DNS",
  "DHCP",
  "HTTP",
  "HTTPS",
  "VPN",
  "VLAN",
  "LAN",
  "WAN",
  "OSI model",
  "Routing Protocols (BGP, OSPF, RIP)",
  "Wireshark",
  "Ethical Hacking",
  "Penetration Testing",
  "Network Security",
  "Cryptography",
  "Firewalls",
  "Intrusion Detection Systems (IDS)",
  "Security Information and Event Management (SIEM)",
  "Vulnerability Assessment",
  "Threat Intelligence",
  "Linux (Ubuntu, CentOS, Debian, Red Hat)",
  "Windows Server",
  "MacOS",
  "Unix",
  "Git",
  "SVN",
  "Mercurial",
  "Unit Testing",
  "Integration Testing",
  "Regression Testing",
  "Load Testing",
  "Performance Testing",
  "Test Automation (Selenium, Cypress, Appium)",
  "Adobe XD",
  "Sketch",
  "Figma",
  "Wireframing",
  "Prototyping",
  "Usability Testing",
  "User Research",
  "Responsive Design",
  "Scrum",
  "Kanban",
  "Lean",
  "Agile Development",
  "Agile Project Management Tools (Jira, Trello, Asana)",
  "Arduino",
  "Raspberry Pi",
  "AVR Microcontrollers",
  "ARM Architecture",
  "Embedded C",
  "FPGA",
  "Ethereum",
  "Solidity",
  "Smart Contracts",
  "Hyperledger Fabric",
  "Corda",
  "Blockchain Development",
  "Qiskit",
  "Cirq",
  "Quantum Algorithms",
  "Quantum Gates",
  "Quantum Circuit Design",
  "AR/VR Development",
  "Unity3D",
  "Unreal Engine",
  "Game Development",
  "OpenGL",
  "DirectX",
  "3D Modeling",
  "Motion Capture",
  "Character Rigging",
  "Animation",
  "UI/UX Design",
  "Product Management",
  "Market Research",
  "Business Analysis",
  "Financial Modeling",
  "Data Visualization",
  "Dashboarding",
  "Power BI",
  "Tableau",
  "Data Warehousing",
  "ETL Processes",
  "Business Intelligence",
  "Customer Relationship Management (CRM)",
  "Enterprise Resource Planning (ERP)",
  "Salesforce",
  "Microsoft Dynamics",
  "SAP",
  "ERP Implementation",
  "Supply Chain Management",
  "Quality Management",
  "Risk Management",
  "Six Sigma",
  "Lean Manufacturing",
  "Continuous Improvement",
  "ISO Standards",
  "Business Process Optimization",
  "Change Management",
  "Strategic Planning",
  "Project Management",
  "Agile Methodologies",
  "Scrum",
  "Kanban",
  "Lean Six Sigma",
  "PRINCE2",
  "ITIL",
  "Risk Management",
  "Stakeholder Management",
  "Budgeting",
  "Resource Allocation",
  "Time Management",
  "Conflict Resolution",
  "Negotiation",
  "Presentation Skills",
  "Leadership",
  "Team Building",
  "Cross-functional Team Leadership",
  "Remote Team Management",
  "Emotional Intelligence",
  "Cultural Intelligence",
  "Problem-solving",
  "Decision-making",
  "Critical Thinking",
  "Analytical Skills",
  "Creativity",
  "Adaptability",
  "Resilience",
  "Communication Skills",
  "Written Communication",
  "Verbal Communication",
  "Interpersonal Skills",
  "Collaboration",
  "Public Speaking",
  "Active Listening",
  "Time Management",
  "Organization",
  "Attention to Detail",
  "Prioritization",
  "Goal Setting",
  "Self-motivation",
  "Self-discipline",
  "Conflict Resolution",
  "Networking",
  "Customer Service",
  "Sales Skills",
  "Marketing Skills",
  "Content Writing",
  "Copywriting",
  "SEO",
  "Social Media Marketing",
  "Email Marketing",
  "Content Management Systems (CMS)",
  "WordPress",
  "Drupal",
  "Joomla",
  "Shopify",
  "Magento",
  "E-commerce",
  "Digital Marketing Strategy",
  "Search Engine Marketing (SEM)",
  "Search Engine Optimization (SEO)",
  "Social Media Management",
  "Content Marketing",
  "Email Marketing",
  "Pay-per-click (PPC) Advertising",
  "Affiliate Marketing",
  "Influencer Marketing",
  "Web Analytics",
  "Google Analytics",
  "Facebook Ads Manager",
  "LinkedIn Ads",
  "Twitter Ads",
  "Instagram Ads",
  "YouTube Ads",
  "Conversion Rate Optimization (CRO)",
  "Lead Generation",
  "Marketing Automation",
  "A/B Testing",
  "User Experience (UX)",
  "User Interface (UI) Design",
  "Wireframing",
  "Prototyping",
  "Usability Testing",
  "Interaction Design",
  "Visual Design",
  "Information Architecture",
  "User Research",
  "Responsive Design",
  "Mobile App Design",
  "Web Design",
  "Graphic Design",
  "Logo Design",
  "Illustration",
  "Typography",
  "Color Theory",
  "Print Design",
  "Packaging Design",
  "Motion Graphics",
  "Video Editing",
  "Photography",
  "Photo Editing",
  "Adobe Creative Suite (Photoshop, Illustrator, InDesign, Premiere Pro, After Effects)",
  "Sketch",
  "Figma",
  "InVision",
  "Adobe XD",
  "Zeplin",
  "Marvel",
  "Axure RP",
  "Balsamiq",
  "User Interface (UI) Design",
  "User Experience (UX) Design",
  "Interaction Design",
  "Information Architecture",
  "Wireframing",
  "Prototyping",
  "Usability Testing",
  "User Research",
  "Responsive Design",
  "Mobile App Design",
  "Web Design",
  "Graphic Design",
  "Logo Design",
  "Illustration",
  "Typography",
  "Color Theory",
  "Print Design",
  "Packaging Design",
  "Motion Graphics",
  "Video Editing",
  "Photography",
  "Photo Editing",
  "Adobe Creative Suite (Photoshop, Illustrator, InDesign, Premiere Pro, After Effects)",
  "Sketch",
  "Figma",
  "InVision",
  "Adobe XD",
  "Zeplin",
  "Marvel",
  "Axure RP",
  "Balsamiq",
  "User Interface (UI) Design",
  "User Experience (UX) Design",
  "Interaction Design",
  "Information Architecture",
  "Wireframing",
  "Prototyping",
  "Usability Testing",
  "User Research",
  "Responsive Design",
  "Mobile App Design",
  "Web Design",
  "Graphic Design",
  "Logo Design",
  "Illustration",
  "Typography",
  "Color Theory",
  "Print Design",
  "Packaging Design",
  "Motion Graphics",
  "Video Editing",
  "Photography",
  "Photo Editing",
  "Adobe Creative Suite (Photoshop, Illustrator, InDesign, Premiere Pro, After Effects)",
  "Sketch",
  "Figma",
  "InVision",
  "Adobe XD",
  "Zeplin",
  "Marvel",
  "Axure RP",
  "Balsamiq",
  "User Interface (UI) Design",
  "User Experience (UX) Design",
  "Interaction Design",
  "Information Architecture",
  "Wireframing",
  "Prototyping",
  "Usability Testing",
  "User Research",
  "Responsive Design",
  "Mobile App Design",
  "Web Design",
  "Graphic Design",
  "Logo Design",
  "Illustration",
  "Typography",
  "Color Theory",
  "Print Design",
  "Packaging Design",
  "Motion Graphics",
  "Video Editing",
  "Photography",
  "Photo Editing",
  "Adobe Creative Suite (Photoshop, Illustrator, InDesign, Premiere Pro, After Effects)",
  "Sketch",
  "Figma",
  "InVision",
  "Adobe XD",
  "Zeplin",
  "Marvel",
  "Axure RP",
  "Balsamiq"
]);
